export const ids = {
  document: "00000000-0000-4000-8000-000000000001",
  project: "00000000-0000-4000-8000-000000000002",
  section: "00000000-0000-4000-8000-000000000003",
  narration: "00000000-0000-4000-8000-000000000004",
  helloToken: "00000000-0000-4000-8000-000000000005",
  worldToken: "00000000-0000-4000-8000-000000000006",
  visibility: "00000000-0000-4000-8000-000000000007",
  manifest: "00000000-0000-4000-8000-000000000008",
  build: "00000000-0000-4000-8000-000000000009",
  videoSource: "00000000-0000-4000-8000-000000000010",
  stillSource: "00000000-0000-4000-8000-000000000011",
  audioSource: "00000000-0000-4000-8000-000000000012",
  placeholderSource: "00000000-0000-4000-8000-000000000013",
  videoEvent: "00000000-0000-4000-8000-000000000014",
  stillEvent: "00000000-0000-4000-8000-000000000015",
  audioEvent: "00000000-0000-4000-8000-000000000016",
  placeholderEvent: "00000000-0000-4000-8000-000000000017",
  transition: "00000000-0000-4000-8000-000000000018",
  marker: "00000000-0000-4000-8000-000000000019",
  report: "00000000-0000-4000-8000-000000000020",
  issue: "00000000-0000-4000-8000-000000000021",
} as const;

export const documentHash = `sha256:${"a".repeat(64)}`;
export const manifestHash = `sha256:${"b".repeat(64)}`;
const videoHash = `sha256:${"c".repeat(64)}`;
const stillHash = `sha256:${"d".repeat(64)}`;
const audioHash = `sha256:${"e".repeat(64)}`;

export const validScriptDocument: ScriptDocumentV1 = {
  schemaVersion: "script-document/v1",
  id: ids.document,
  projectId: ids.project,
  title: "Phase 1 contract sample",
  activeDraft: {
    blocks: [
      {
        type: "section",
        id: ids.section,
        orderKey: "a0",
        title: "Opening",
        version: 1,
      },
      {
        type: "narration",
        id: ids.narration,
        orderKey: "a1",
        text: "Hello world.",
        tokens: [
          {
            id: ids.helloToken,
            value: "Hello",
            startOffset: 0,
            endOffset: 5,
          },
          {
            id: ids.worldToken,
            value: "world",
            startOffset: 6,
            endOffset: 11,
          },
        ],
        hostVisibilitySpans: [
          {
            id: ids.visibility,
            range: {
              blockId: ids.narration,
              startTokenId: ids.helloToken,
              endTokenId: ids.worldToken,
              startAffinity: "before",
              endAffinity: "after",
              quotedText: "Hello world",
              anchorVersion: 1,
            },
            state: "voiceover",
            source: "authored",
            version: 1,
          },
        ],
        visualEvents: [
          {
            id: ids.placeholderEvent,
            range: {
              blockId: ids.narration,
              startTokenId: ids.helloToken,
              endTokenId: ids.worldToken,
              startAffinity: "before",
              endAffinity: "after",
              quotedText: "Hello world",
              anchorVersion: 1,
            },
            source: {
              kind: "placeholder",
              description: "Choose an opening visual",
              unresolvedVisual: true,
            },
            presentationMode: "full_frame",
            framingPolicy: "native",
            motionPreset: "none",
            audioPolicy: "mute",
            layer: 5,
            transitionIn: null,
            transitionOut: null,
            timingOverrides: null,
            status: "unresolved",
            version: 1,
          },
        ],
        timingPolicy: "narration_spine",
        state: "active",
        notes: [],
        version: 1,
      },
    ],
  },
  ideaOutline: [],
  extras: [],
  liveHeadSequence: 1,
  liveStateVector: "AQID",
  liveContentHash: documentHash,
};

export const validTimelineManifest: TimelineManifestV1 = {
  schemaVersion: "timeline-manifest/v1",
  id: ids.manifest,
  buildId: ids.build,
  sourceDocument: {
    documentId: ids.document,
    projectId: ids.project,
    liveHeadSequence: 1,
    contentHash: documentHash,
  },
  timeline: {
    frameRate: { numerator: 24000, denominator: 1001 },
    width: 1920,
    height: 1080,
    audioSampleRate: 48000,
    startFrame: 0,
    durationFrames: 240,
  },
  tracks: [
    { id: "track-01", kind: "video", index: 1, name: "Primary picture" },
    { id: "track-02", kind: "video", index: 2, name: "Research clips" },
    { id: "track-03", kind: "video", index: 3, name: "B-roll and stills" },
    { id: "track-04", kind: "video", index: 4, name: "Graphics and overlays" },
    { id: "track-05", kind: "video", index: 5, name: "Placeholders" },
    { id: "track-06", kind: "audio", index: 1, name: "Narration 1" },
    { id: "track-07", kind: "audio", index: 2, name: "Narration 2" },
    { id: "track-08", kind: "audio", index: 3, name: "Source audio 1" },
    { id: "track-09", kind: "audio", index: 4, name: "Source audio 2" },
    { id: "track-10", kind: "audio", index: 5, name: "Music and SFX" },
    { id: "track-11", kind: "subtitle", index: 1, name: "English subtitles" },
  ],
  sources: [
    {
      id: ids.videoSource,
      kind: "video",
      path: "Media/Local Clips/video/source.mov",
      contentHash: videoHash,
      durationFrames: 240,
      frameRate: { numerator: 24, denominator: 1 },
      width: 1920,
      height: 1080,
      audioChannels: 2,
    },
    {
      id: ids.stillSource,
      kind: "still",
      path: "Media/Local Images/still/source.png",
      contentHash: stillHash,
      width: 1600,
      height: 900,
    },
    {
      id: ids.audioSource,
      kind: "audio",
      path: "Media/Narration/block/source.wav",
      contentHash: audioHash,
      durationFrames: 240,
      sampleRate: 48000,
      channels: 1,
    },
    {
      id: ids.placeholderSource,
      kind: "placeholder",
      label: "UNRESOLVED VISUAL",
      reason: "No media has been selected",
    },
  ],
  events: [
    {
      id: ids.videoEvent,
      kind: "video",
      sourceId: ids.videoSource,
      trackId: "track-02",
      trackKind: "video",
      recordRange: { startFrame: 0, durationFrames: 120 },
      sourceRange: { startFrame: 24, durationFrames: 120 },
      timingPrecision: "word",
      alignmentVersion: "speech-alignment-v1",
      provenance: {
        documentId: ids.document,
        blockId: ids.narration,
        authoringKind: "visual_event",
        authoringId: ids.videoEvent,
      },
    },
    {
      id: ids.stillEvent,
      kind: "still",
      sourceId: ids.stillSource,
      trackId: "track-03",
      trackKind: "video",
      recordRange: { startFrame: 120, durationFrames: 96 },
      timingPrecision: "word",
      alignmentVersion: "speech-alignment-v1",
      provenance: {
        documentId: ids.document,
        blockId: ids.narration,
        authoringKind: "visual_event",
        authoringId: ids.stillEvent,
      },
    },
    {
      id: ids.audioEvent,
      kind: "audio",
      sourceId: ids.audioSource,
      trackId: "track-06",
      trackKind: "audio",
      recordRange: { startFrame: 0, durationFrames: 240 },
      sourceRange: { startFrame: 0, durationFrames: 240 },
      timingPrecision: "word",
      alignmentVersion: "speech-alignment-v1",
      provenance: {
        documentId: ids.document,
        blockId: ids.narration,
        authoringKind: "narration_block",
        authoringId: ids.narration,
      },
    },
    {
      id: ids.placeholderEvent,
      kind: "placeholder",
      sourceId: ids.placeholderSource,
      trackId: "track-05",
      trackKind: "video",
      recordRange: { startFrame: 216, durationFrames: 24 },
      timingPrecision: "word",
      alignmentVersion: "speech-alignment-v1",
      provenance: {
        documentId: ids.document,
        blockId: ids.narration,
        authoringKind: "visual_event",
        authoringId: ids.placeholderEvent,
      },
    },
  ],
  transitions: [
    {
      id: ids.transition,
      kind: "hard_cut",
      fromEventId: ids.videoEvent,
      toEventId: ids.stillEvent,
      atFrame: 120,
      durationFrames: 0,
    },
  ],
  markers: [
    {
      id: ids.marker,
      state: "placed",
      frame: 72,
      name: "Review this beat",
      note: "Review this beat\nCheck the visual choice.",
      color: "Blue",
      provenance: {
        documentId: ids.document,
        blockId: ids.narration,
        authoringKind: "script_marker",
        authoringId: ids.marker,
      },
    },
  ],
};

export const validBuildReport: BuildReportV1 = {
  schemaVersion: "build-report/v1",
  id: ids.report,
  buildId: ids.build,
  buildClass: "preview",
  status: "ready_with_warnings",
  temporaryNarration: true,
  sourceDocument: validTimelineManifest.sourceDocument,
  manifest: {
    id: ids.manifest,
    contentHash: manifestHash,
  },
  timeline: validTimelineManifest.timeline,
  summary: {
    sourceCount: 4,
    eventCount: 4,
    markerCount: 1,
    placedCount: 4,
    placeholderCount: 1,
    manualCompletionCount: 0,
    warningCount: 1,
    errorCount: 0,
  },
  eventResults: validTimelineManifest.events.map((event) => ({
    eventId: event.id,
    disposition: event.kind === "placeholder" ? "placeholder" : "placed",
    sourceId: event.sourceId,
    trackId: event.trackId,
    trackKind: event.trackKind,
    recordRange: event.recordRange,
    message:
      event.kind === "placeholder"
        ? "Placed a labeled unresolved-visual slate."
        : "Placed from the canonical manifest.",
  })),
  issues: [
    {
      id: ids.issue,
      severity: "warning",
      code: "TEMPORARY_NARRATION",
      message: "The narration is temporary synthetic speech.",
      entity: { kind: "block", id: ids.narration },
    },
  ],
  manualCompletionItems: [],
};

export const validCompilerDependencies: CompilerDependenciesV1 = {
  schemaVersion: "compiler-dependencies/v1",
  build: {
    buildId: ids.build,
    manifestId: ids.manifest,
    reportId: ids.report,
    buildClass: "preview",
    timeline: {
      frameRate: { numerator: 24000, denominator: 1001 },
      width: 1920,
      height: 1080,
      audioSampleRate: 48000,
      startFrame: 0,
    },
  },
  tracks: validTimelineManifest.tracks,
  roles: {
    presenterTrackId: "track-01",
    placeholderTrackId: "track-05",
    narrationTrackId: "track-06",
    sourceAudioTrackId: "track-08",
  },
  narration: [
    {
      blockId: ids.narration,
      blockRevision: 1,
      assetId: "f".repeat(64),
      status: "ready",
      textHash: documentHash,
      audioHash,
      audio: {
        locator: "Media/Narration/block/source.wav",
        durationSamples: 480000,
        sampleRate: 48000,
        channels: 1,
      },
      timing: {
        recordVersion: "provider-timing/v1",
        contentHash: manifestHash,
        alignmentVersion: "aws-polly-neural-v1",
        precision: "word_start_with_derived_end",
        marks: [
          {
            kind: "word",
            timeMs: 0,
            startUtf16: 0,
            endUtf16: 5,
            value: "Hello",
          },
          {
            kind: "word",
            timeMs: 450,
            startUtf16: 6,
            endUtf16: 11,
            value: "world",
          },
        ],
      },
    },
  ],
  resolvedVisuals: [
    {
      mediaReferenceId: ids.videoSource,
      source: validTimelineManifest.sources.find((source) => source.kind === "video")!,
      sourceStartFrame: 24,
      sourceAudio: {
        source: validTimelineManifest.sources.find((source) => source.kind === "audio")!,
        sourceStartFrame: 24,
      },
    },
  ],
};
import type {
  BuildReportV1,
  CompilerDependenciesV1,
  ScriptDocumentV1,
  TimelineManifestV1,
} from "../src/generated/contracts.js";
